In [ ]:
import pandas as pd
import numpy as np
import torch
from torch.utils.data import DataLoader
from sklearn.preprocessing import StandardScaler
from src.deep_learning.preprocessing import scale_df, TimeSeriesDataset
from src.deep_learning.finetuning import objective
import joblib
import optuna
from functools import partial

In [ ]:
random_seed = 42
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed(random_seed)
torch.cuda.manual_seed_all(random_seed)
torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

In [ ]:
train_df = pd.read_parquet(r"..\data\processed\train.parquet")
val_df = pd.read_parquet(r"..\data\processed\val.parquet")
test_df = pd.read_parquet(r"..\data\processed\test.parquet")
consumption_df = pd.read_parquet(r"..\data\processed\consumption_fe.parquet")

In [ ]:
train_df.head(1)

,date,consumption,hour_sin,hour_cos,day_sin,day_cos,month_sin,month_cos
0,2018-01-01,27412.81,0.0,1.0,0.0,1.0,0.5,0.866025

In [ ]:
feature_cols = ["consumption",
    "hour_sin", "hour_cos",
    "day_sin", "day_cos",
    "month_sin", "month_cos"
]

target = "consumption"

scale_cols = ["consumption"]

In [ ]:
scaler = StandardScaler()

scaler_path = r"..\models\scaler_ft.pkl"

train_scaled = scale_df(df=train_df, train=True, scaler=scaler, scale_cols=scale_cols)

joblib.dump(scaler, scaler_path)

val_scaled = scale_df(df=val_df, train=False, scaler=scaler, scale_cols=scale_cols)

test_scaled = scale_df(df=test_df, train=False, scaler=scaler, scale_cols=scale_cols)

In [ ]:
train_scaled.head(2)

,date,consumption,hour_sin,hour_cos,day_sin,day_cos,month_sin,month_cos
0,2018-01-01 00:00:00,-1.350096,0.000000,1.000000,0.0,1.0,0.5,0.866025
1,2018-01-01 01:00:00,-1.539594,0.258819,0.965926,0.0,1.0,0.5,0.866025

In [ ]:
window_size = 168
horizon = 24
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [ ]:
train_dataset = TimeSeriesDataset(df=train_scaled, feature_cols=feature_cols, target_col=target, window_size=window_size, horizon=horizon) 
val_dataset = TimeSeriesDataset(df=val_scaled, feature_cols=feature_cols, target_col=target, window_size=window_size, horizon=horizon) 
test_dataset = TimeSeriesDataset(df=test_scaled, feature_cols=feature_cols, target_col=target, window_size=window_size, horizon=horizon)

In [ ]:
batch_size = 32

train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size, shuffle=False)
test_loader = DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

In [ ]:
study = optuna.create_study(
    study_name="lstm_finetuning",
    direction="minimize",
    sampler=optuna.samplers.TPESampler(seed=random_seed),
    pruner=optuna.pruners.MedianPruner(n_warmup_steps=5)
)

[I 2026-02-11 12:56:13,687] A new study created in memory with name: lstm_finetuning

In [ ]:
objective_fn = partial(objective,
                        train_loader=train_loader,
                        val_loader=val_loader,
                        input_size=len(feature_cols),
                        horizon=horizon,
                        device=device,
                        num_epochs=50)

In [ ]:
study.optimize(objective_fn, n_trials=50)

print("Best validation loss:", study.best_trial.value)
print("Best hyperparameters:")
print(study.best_trial.params)

[I 2026-02-11 12:58:06,662] Trial 0 finished with value: 0.023707333226899226 and parameters: {'hidden_size': 96, 'num_layers': 3, 'dropout': 0.36599697090570255, 'lin_features': 128, 'lr': 0.0001432249371823026, 'weight_decay': 4.207053950287936e-06}. Best is trial 0 with value: 0.023707333226899226.
[I 2026-02-11 12:58:37,101] Trial 1 finished with value: 0.6543192066469862 and parameters: {'hidden_size': 32, 'num_layers': 3, 'dropout': 0.3005575058716044, 'lin_features': 144, 'lr': 0.00010485387725194633, 'weight_decay': 0.00757947995334801}. Best is trial 0 with value: 0.023707333226899226.
[I 2026-02-11 13:05:48,769] Trial 2 finished with value: 0.023477978933284797 and parameters: {'hidden_size': 224, 'num_layers': 1, 'dropout': 0.09091248360355031, 'lin_features': 48, 'lr': 0.0002014847788415866, 'weight_decay': 0.0001256104370001356}. Best is trial 2 with value: 0.023477978933284797.
[I 2026-02-11 13:06:52,812] Trial 3 finished with value: 0.024292064073073855 and parameters: {'hidden_size': 128, 'num_layers': 1, 'dropout': 0.30592644736118974, 'lin_features': 32, 'lr': 0.00019594972058679176, 'weight_decay': 2.9204338471814107e-05}. Best is trial 2 with value: 0.023477978933284797.
[I 2026-02-11 13:09:26,062] Trial 4 finished with value: 0.019635534227192646 and parameters: {'hidden_size': 128, 'num_layers': 3, 'dropout': 0.09983689107917987, 'lin_features': 112, 'lr': 0.0003912141628549697, 'weight_decay': 1.5339162591163623e-06}. Best is trial 4 with value: 0.019635534227192646.
[I 2026-02-11 13:10:29,507] Trial 5 pruned.
[I 2026-02-11 13:10:47,242] Trial 6 pruned.
[I 2026-02-11 13:11:10,580] Trial 7 pruned.
[I 2026-02-11 13:12:16,689] Trial 8 pruned.
[I 2026-02-11 13:14:44,499] Trial 9 pruned.
[I 2026-02-11 13:23:31,337] Trial 10 finished with value: 0.018621335476099315 and parameters: {'hidden_size': 256, 'num_layers': 2, 'dropout': 0.1843643863605487, 'lin_features': 80, 'lr': 0.0004667362076270232, 'weight_decay': 1.4285676124002462e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 13:31:52,539] Trial 11 finished with value: 0.01982909296456641 and parameters: {'hidden_size': 256, 'num_layers': 2, 'dropout': 0.17951461563024992, 'lin_features': 80, 'lr': 0.0004948790413499528, 'weight_decay': 1.083288527960517e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 13:40:44,905] Trial 12 finished with value: 0.019649449669550397 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.21838072053294139, 'lin_features': 80, 'lr': 0.0004047475923597452, 'weight_decay': 1.043821812118888e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 13:46:09,581] Trial 13 finished with value: 0.02173433045069913 and parameters: {'hidden_size': 192, 'num_layers': 2, 'dropout': 0.15388950578114163, 'lin_features': 112, 'lr': 0.0005911043334995636, 'weight_decay': 5.336865903178938e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 13:46:28,876] Trial 14 pruned.
[I 2026-02-11 13:48:53,774] Trial 15 pruned.
[I 2026-02-11 13:49:31,278] Trial 16 pruned.
[I 2026-02-11 13:49:50,896] Trial 17 pruned.
[I 2026-02-11 13:53:08,453] Trial 18 pruned.
[I 2026-02-11 13:55:03,118] Trial 19 pruned.
[I 2026-02-11 13:55:27,118] Trial 20 pruned.
[I 2026-02-11 14:02:56,182] Trial 21 finished with value: 0.020418158321480223 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.2180499167861401, 'lin_features': 80, 'lr': 0.0004833160582758555, 'weight_decay': 1.1336962038208903e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:10:57,708] Trial 22 finished with value: 0.018751744718923706 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.13689757550204049, 'lin_features': 64, 'lr': 0.0003978457677327601, 'weight_decay': 2.4699107400156674e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:17:43,288] Trial 23 finished with value: 0.019409917777060186 and parameters: {'hidden_size': 256, 'num_layers': 2, 'dropout': 0.15590980162772455, 'lin_features': 48, 'lr': 0.00026855169717792906, 'weight_decay': 2.6473255431369284e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:24:28,299] Trial 24 finished with value: 0.019479474346067276 and parameters: {'hidden_size': 256, 'num_layers': 2, 'dropout': 0.15310577939587766, 'lin_features': 48, 'lr': 0.0002652315308801802, 'weight_decay': 3.7189381145683037e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:26:42,803] Trial 25 pruned.
[I 2026-02-11 14:28:58,630] Trial 26 pruned.
[I 2026-02-11 14:36:41,230] Trial 27 finished with value: 0.01917921381202785 and parameters: {'hidden_size': 256, 'num_layers': 2, 'dropout': 0.26558613140800774, 'lin_features': 32, 'lr': 0.0007250917681224058, 'weight_decay': 2.3394846395069468e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:39:03,876] Trial 28 pruned.
[I 2026-02-11 14:40:08,337] Trial 29 pruned.
[I 2026-02-11 14:42:32,125] Trial 30 pruned.
[I 2026-02-11 14:44:55,982] Trial 31 pruned.
[I 2026-02-11 14:54:58,540] Trial 32 finished with value: 0.018994548834360036 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.23518807999518182, 'lin_features': 64, 'lr': 0.0005080514152261401, 'weight_decay': 3.116618903320651e-06}. Best is trial 10 with value: 0.018621335476099315.
[I 2026-02-11 14:57:14,227] Trial 33 pruned.
[I 2026-02-11 15:02:31,513] Trial 34 finished with value: 0.01853488871660164 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.23337064414247433, 'lin_features': 32, 'lr': 0.0007495878553923854, 'weight_decay': 3.4783903695264332e-06}. Best is trial 34 with value: 0.01853488871660164.
[I 2026-02-11 15:12:28,141] Trial 35 finished with value: 0.01939041803914039 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.23020145759121968, 'lin_features': 96, 'lr': 0.0004482858192655789, 'weight_decay': 1.632972699318051e-05}. Best is trial 34 with value: 0.01853488871660164.
[I 2026-02-11 15:13:38,184] Trial 36 pruned.
[I 2026-02-11 15:21:50,088] Trial 37 finished with value: 0.019034690294407387 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.12482137691649739, 'lin_features': 16, 'lr': 0.0008132836884791083, 'weight_decay': 1.6293160737927684e-06}. Best is trial 34 with value: 0.01853488871660164.
[I 2026-02-11 15:23:05,927] Trial 38 pruned.
[I 2026-02-11 15:24:52,039] Trial 39 pruned.
[I 2026-02-11 15:28:16,719] Trial 40 pruned.
[I 2026-02-11 15:34:24,435] Trial 41 finished with value: 0.019480749769627277 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.12055685625421154, 'lin_features': 16, 'lr': 0.0008031453670203028, 'weight_decay': 1.88477914081233e-06}. Best is trial 34 with value: 0.01853488871660164.
[I 2026-02-11 15:37:08,217] Trial 42 pruned.
[I 2026-02-11 15:39:15,113] Trial 43 pruned.
[I 2026-02-11 15:51:05,139] Trial 44 finished with value: 0.017443829425781304 and parameters: {'hidden_size': 224, 'num_layers': 2, 'dropout': 0.17498226896177801, 'lin_features': 32, 'lr': 0.0006477616087737383, 'weight_decay': 3.680266245751368e-06}. Best is trial 44 with value: 0.017443829425781304.
[I 2026-02-11 15:56:19,730] Trial 45 finished with value: 0.01981398547873513 and parameters: {'hidden_size': 160, 'num_layers': 2, 'dropout': 0.17647814742681328, 'lin_features': 32, 'lr': 0.0006943921250482595, 'weight_decay': 3.6117667295102812e-06}. Best is trial 44 with value: 0.017443829425781304.
[I 2026-02-11 15:57:49,921] Trial 46 pruned.
[I 2026-02-11 15:59:48,228] Trial 47 pruned.
[I 2026-02-11 16:02:20,239] Trial 48 pruned.
[I 2026-02-11 16:04:56,245] Trial 49 pruned.

Best validation loss: 0.017443829425781304
Best hyperparameters:
{'hidden_size': 224, 'num_layers': 2, 'dropout': 0.17498226896177801, 'lin_features': 32, 'lr': 0.0006477616087737383, 'weight_decay': 3.680266245751368e-06}